# Tensors : PG - Low Level APIs

In [2]:
# surpress warning
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

sess = tf.Session()

In [8]:
my_image = tf.zeros([10,299,299,3])
r = tf.rank(my_image)
print(r)
print("rank is", sess.run(r))

Tensor("Rank_5:0", shape=(), dtype=int32)
rank is 4


In [23]:
a_mat = tf.Variable([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a_scalar = a_mat[1,0]

init = tf.global_variables_initializer()
sess.run(init)

print(a_mat)
print(a_mat.shape)
print(a_scalar)
print("mat[1,0] =", sess.run(a_scalar))
print("mat = ", sess.run(a_mat))

<tf.Variable 'Variable_5:0' shape=(4, 3) dtype=int32_ref>
(4, 3)
Tensor("strided_slice_5:0", shape=(), dtype=int32)
mat[1,0] = 4
mat =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Reshape

In [17]:
b = tf.reshape(a_mat, [2,3,2])
print(b)
print(sess.run(b))

b = tf.reshape(a_mat, [4,-1])
print(b)
print(sess.run(b))

b = tf.reshape(a_mat, [-1])
print(b)
print(sess.run(b))

Tensor("Reshape_4:0", shape=(2, 3, 2), dtype=int32)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Tensor("Reshape_5:0", shape=(4, 3), dtype=int32)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Tensor("Reshape_6:0", shape=(12,), dtype=int32)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Data types, eval, print

In [25]:
tf_int = tf.constant([1, 2, 3], dtype=tf.int16)
tf_float = tf.cast(tf_int, dtype=tf.float32)
mul = tf_int * tf_int
print(str(tf_int))
print(str(tf_float))

print(str(mul))

print(str(mul.eval(session=sess)))

Tensor("Const_6:0", shape=(3,), dtype=int16)
Tensor("Cast_4:0", shape=(3,), dtype=float32)
Tensor("mul_3:0", shape=(3,), dtype=int16)
[1 4 9]


In [30]:
p = tf.placeholder(tf.float32)
t = p + 3.

with sess.as_default():
    r = t.eval(feed_dict={p: 2.})

print("r =", r)

r = 5.0


In [35]:
tf_int = tf.constant([1, 2, 3], dtype=tf.int16)
mul = tf_int * tf_int

mul = tf.Print(mul, [mul])
result = mul + 1
print(mul)
print(result)

Tensor("Print_4:0", shape=(3,), dtype=int16)
Tensor("add_8:0", shape=(3,), dtype=int16)
