## Unit 5.3 : Diagonalization of Matrices

### Definition

An matrix $ A_{n \times n} $ is called diagonalizable if $ A = PDP^{-1} $ for some diagonal matrix $ D_{n \times n} $  
and some invertible matrix $ P_{n \times n} $ 

### Example: stochastic matrix

每年城鄉人口流動率矩陣:

|To\From|City|Suburbs|
|-      |-|-|
|City   |.85|.03|
|Suburb |.15|.97|

$ A = \begin{bmatrix} .85 & .03 \\ .15 & .97 \end{bmatrix} $

目前城鄉人口數 $ \vec{p} = \begin{bmatrix} 500 \\ 700 \end{bmatrix} $

下一年城鄉人口數 $ = A \vec{p} = \begin{bmatrix} .85 & .03 \\ .15 & .97 \end{bmatrix} $
$ \begin{bmatrix} 500 \\ 700 \end{bmatrix} $

過了 m 年後的城鄉人口數 $ = A^m \vec{p} $

如果 A 是 diagonal matrix, 矩陣的次方只需要將 diagonal entry 次方即可

$ A = PDP^{-1} $ where $ P = \begin{bmatrix} -1&1 \\ 1&5 \end{bmatrix} $,
$ D = \begin{bmatrix} .82 & 0 \\ 0 & 1 \end{bmatrix} $

$ A^3 = (PDP^{-1}) \ (PDP^{-1}) \ (PDP^{-1}) = P D^3 P^{-1}  $

> 可對角化的矩陣可以方便的進行次方運算。

- How to know A is diagonalizable or not ?
- If yes, how to get D and P ?

### Observation 1

matrix $ B = \begin{bmatrix} 2 & 1 \\ 0 & 1 \end{bmatrix} $  
Characteristic polynomial = (2-t) (1-t)  
Eigenvalues, Eigenspaces:

1 (mul:1), Span { $ \begin{bmatrix} 1\\-1 \end{bmatrix} $ }

2 (mul:1), Span { $ \begin{bmatrix} 1\\0 \end{bmatrix} $ }

將 B 矩陣 乘上 vectors in basis of eigenspaces, 然後接上由 eigenvalue 組成的對角矩陣

$ \begin{bmatrix} 2 & 1 \\ 0 & 1 \end{bmatrix} $
$ \ \begin{bmatrix} 1 & 1 \\ -1 & 0 \end{bmatrix} $
$ = \begin{bmatrix} 1 & 2 \\ -1 & 0 \end{bmatrix} $
$ = \begin{bmatrix} 1 & 1 \\ -1 & 0 \end{bmatrix} $
$ \ \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix} $

矩陣P 為 eigenspaces 中的 basis vector 組成，是 L.I., invertible。  
矩陣D 為 eigenvalues 組成的 diagonal matrix。

如此可得 $ BP = PD \ \ \to \ \ B = PDP^{-1} $

In [2]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(precision=3)
B = np.array([[2, 1],
              [0, 1]])

e_vals, e_vecs = la.eig(B)
print('B matrix: \n%s' % B)
print('eigen values: \n%s' % e_vals)
print('eigen vectors: \n%s' % e_vecs)

D = np.diag(e_vals)
P = e_vecs
P_inv = la.inv(P)
# B = P D P_inv
print('P matrix : \n%s' % P)
print('D matrix : \n%s' % D)
print('P inverse: \n%s' % P_inv)
B_verify = P.dot(D).dot(P_inv)
print('\n VERIFY B = P D P_inv: \n%s' % B_verify)

B matrix: 
[[2 1]
 [0 1]]
eigen values: 
[ 2.  1.]
eigen vectors: 
[[ 1.    -0.707]
 [ 0.     0.707]]
P matrix : 
[[ 1.    -0.707]
 [ 0.     0.707]]
D matrix : 
[[ 2.  0.]
 [ 0.  1.]]
P inverse: 
[[ 1.     1.   ]
 [ 0.     1.414]]

 VERIFY B = P D P_inv: 
[[ 2.  1.]
 [ 0.  1.]]


### Observation 2

matrix $ A = \begin{bmatrix} -1 & 0 & 0 \\ 0 & 1 & 2 \\ 0 & 2 & 1 \end{bmatrix} $  
Characteristic polynomial = $ -(t+1)^2 (t-3) $
Eigenvalues, Eigenspaces:

-1 (mul:2), Span { $ \begin{bmatrix} 1\\0\\0 \end{bmatrix} $ , $ \begin{bmatrix} 0\\1\\-1 \end{bmatrix} $ }

 3 (mul:1), Span { $ \begin{bmatrix} 0\\1\\1 \end{bmatrix} $ }

將 A 矩陣 乘上 vectors in basis of eigenspaces : P, 然後接上由 eigenvalue 組成的對角矩陣D

得 $ AP = PD \ \ \to \ \ A = PDP^{-1} $

matrix $ P = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 1 \\ 0 & -1 & 1 \end{bmatrix} $

matrix $ D = \begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 3 \end{bmatrix} $  

矩陣P 為 eigenspaces 中的 basis vector 組成，是 L.I., invertible。  
矩陣D 為 eigenvalues 組成的 diagonal matrix。

In [3]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(precision=3)
A = np.array([-1,0,0,0,1,2,0,2,1]).reshape(3,3)

e_vals, e_vecs = la.eig(A)
print('A matrix: \n%s' % A)
D = np.diag(e_vals)
P = e_vecs
P_inv = la.inv(P)
# B = P D P_inv
print('P matrix : \n%s' % P)
print('D matrix : \n%s' % D)
print('P inverse: \n%s' % P_inv)
A_verify = P.dot(D).dot(P_inv)
print('\n VERIFY A = P D P_inv: \n%s' % A_verify)

A matrix: 
[[-1  0  0]
 [ 0  1  2]
 [ 0  2  1]]
P matrix : 
[[ 0.     0.     1.   ]
 [ 0.707  0.707  0.   ]
 [ 0.707 -0.707  0.   ]]
D matrix : 
[[ 3.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
P inverse: 
[[ 0.     0.707  0.707]
 [ 0.     0.707 -0.707]
 [ 1.     0.     0.   ]]

 VERIFY A = P D P_inv: 
[[-1.  0.  0.]
 [ 0.  1.  2.]
 [ 0.  2.  1.]]


### Theorem 5.2

可以找到 n 個線性獨立的 eigen vector，就是 可對角化 的矩陣

(a) An matrix $ A_{n \times n} $ is **diagonalizable** iff. there is a basis of $ \mathcal{R}^n $ consisting of eigenvectors of A.

(b) If matrix $ P_{n \times n} $ is an invertible and matrix $ D_{n \times n} $ is a diagonal matrix,  
then $ A = P D P^{-1} $ iff. the columns of P are a basis for $ \mathcal{R}^n $ consisting of eigenvectors of A  
and the diagonal entries of D are the eigenvalues corresponding to the respective columns of P.

### Theorem 5.3

A set of eigenvectors of a square matrix that correspond to distinct eigenvalues is linearly independent.  
來自不同的 eigenvalue 的 eigenvectors 彼此間是線性獨立。

### Corollary 1

Let $ S_1, S_2, \cdots, S_p $ be subsets of p eigenspaces of a square matrix corresponding to p distinct eigenvalues.  
If $ S_i $ is L.I. for all i = 1, 2, ..., p; then the set $ S_1 \cup S_2 \cup \cdots \cup S_p$ is L.I.  
每一個 eigenvalue 對應的 eigenvectors 是 L.I.; 從不同的 eigenvalue 對應的 eigenvectors 為 S1, S2... 子集合 的 聯集 也是 線性獨立。

### Corollary 2

If $ A \in \mathcal{R}^{n \times n} $ has n distinct eigenvalues,  
then $ \mathcal{R}^n $ has a basis consisting of eigenvectors of A.  
i.e., A is diagonalizable.

### Definition: product of linear factors 線性因式

For $ A \in \mathcal{R}^{n \times n} $, the characteristic polynomial of A may be  
factored into a **product of linear factors** if

$ det(A - t \ I_n) = (-1)^n \ (t - \lambda_1) \ (t - \lambda_2) \ \cdots \ (t - \lambda_n) $

Here, $ \lambda_i $ for i = 1, 2, ..., n; do not have to be distinct, but $ \lambda_i \in \mathcal{R} $

### Test for a diagonalizable Matrix

An matrix $ A_{n \times n} $ is diagonalizable iff. BOTH the following conditions are met:

1. The characteristic polynomial of A factors into a product of linear factors.
2. For each eigenvalue of A, its multiplicity equals the dimension of corresponding eigenspace. ( n - rank( $ A - \lambda I_n $ ) )