## Reduced Row Echelon Form

Let $ A \in \mathcal{M}_{m \times n} $

In [1]:
import sympy as sympy
import numpy as np
np.set_printoptions(precision=2, suppress=True)

A = np.array([(1, -2, -1, 3),
              (3, -6, -5, 3),
              (2, -1,  1, 0)])
R = sympy.Matrix(A).rref()
print(R)

(Matrix([
[1.0,   0,   0, -4.0],
[  0, 1.0,   0, -5.0],
[  0,   0, 1.0,  3.0]]), [0, 1, 2])


## Matrix Inversion

$ A,B \in \mathcal{M}_{n \times n}, A \times B = I_n $

In [2]:
A = np.array([(1, 2, 3),
              (2, 5, 6),
              (3, 4, 8)])
B = np.linalg.inv(A)
print('Inverse of A:\n%s\n' % B)

print('A x B is I :\n%s' % A.dot(B))

Inverse of A:
[[-16.   4.   3.]
 [ -2.   1.  -0.]
 [  7.  -2.  -1.]]

A x B is I :
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
